# Generated by Django 4.2.1 on 2024-01-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Create', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='profile',
            field=models.ImageField(default=0, upload_to='pics/'),
        ),
    ]
