# Generated by Django 4.2.1 on 2024-02-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Create', '0002_register_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
